### ISSUE TITLE
consider patching other FSA interfacing methods

### ISSUE THREAD

**Issue by ThaUnknown** [tomayac/opfs-explorer#1]
This is a great extension, and it's honestly something that should be built into the browser, but it's lacking for custom user-defined directories.

Consider patching functions like `window.showDirectoryPicker` and `window.showSaveFilePicker` using a proxy object or a patch function to expose more folder/file handles to the extension.

Is this a good idea?

**Comment by tomayac** [comment]
This is explicitly focused on the OPFS, which is _not_ accessible via the picker methods. So this is not planned.

**Comment by ThaUnknown** [comment]
> This is explicitly focused on the OPFS, which is _not_ accessible via the picker methods. So this is not planned.

yes which is why `consider` is there as it might not be that hard to do
