### ISSUE TITLE
Can't delete files with very long filenames

### ISSUE THREAD

**Issue by karyon** [tomayac/opfs-explorer#12]
![image](https://github.com/tomayac/opfs-explorer/assets/1891915/3f275871-afac-4c10-83eb-0f6be3419c39)
 You can probably guess what happened here :D In any case, I cannot delete these files with OPFS explorer because the delete button is to the right of the filename, the filename is *very* long, and there's no horizontal scrollbar. 

Cheers, and thank you for this project :)

**Comment by tomayac** [comment]
I hope to add a fix for this soon. Haha, and I know what happened here… 😂

**Comment by tomayac** [comment]
(Hopefully) Fixed via https://github.com/tomayac/opfs-explorer/commit/b978453f1cc23fe21ffcd37b61fa1538329071b7.
