### ISSUE TITLE
Did this extension stopped working in Chrome v117?

### ISSUE THREAD

**Issue by proof-llc** [tomayac/opfs-explorer#13]
It used to work but it doesn't work for me anymore. Not sure if I have flag enabled that does this but the tab doesn't show up anymore. I tried the unpacked method as well, without success. Does it work for you?

**Comment by tomayac** [comment]
It's working here. Can you check if you get any errors on chrome://extensions when you inspect the service worker and the errors section?

**Comment by proof-llc** [comment]
No errors, weirdly enough. Uploaded a screenshot showing how I don't get the tab anymore:
<img width="1142" alt="Screenshot 2023-10-02 at 12 12 57 PM" src="https://github.com/tomayac/opfs-explorer/assets/112896565/483d6b9d-7ecf-4feb-a4e6-ff9c668042b7">

**Comment by tomayac** [comment]
Can you paste chrome://version here, please? Will try to get as close as possible to your environment.

**Comment by proof-llc** [comment]
Thank you I appreciate the help. After some debugging, I figured out that it only fails on my work Chrome profile. Other profiles work fine. Very weird. I disabled all chrome extension and reinstalled this one. Still doesn't work. Not sure if because this profile had an older version that it never fully deleted it. One difference I noticed is that the working profile do not show that the service worker is inactive as the work one does.
<img width="410" alt="Screenshot 2023-10-02 at 12 48 05 PM" src="https://github.com/tomayac/opfs-explorer/assets/112896565/69dd3088-3fa6-4791-bd0b-d1d27e1da15b">

**Comment by tomayac** [comment]
One theory could be that your work admin blocks the extension? You can also try a completely fresh Chrome profile just to be on the safe side. In the dialog from your screenshot above, you can copy the ID, search for the corresponding folder on your hard disk, and delete it manually if you believe the folder could have been corrupted.

**Comment by proof-llc** [comment]
the work profile is not tied to an enterprise policy or anything of that kind. The folder is deleted properly - no corruption. given that loading the extension manually with the unpacked method gives same result, i think it may be some setting that is different perhaps in that one profile. i'll close this issue for now given that we lack enough information. i can re-open it once i figure out what it is. Thanks for your help!

**Comment by korywka** [comment]
Hello. The same problem - no tab. Workaround: allow extension in incognito mode and try again in incognito.

**Comment by tomayac** [comment]
> Hello. The same problem - no tab. Workaround: allow extension in incognito mode and try again in incognito.

Interesting. Is this a managed profile? Also, could you paste the output of `chrome://version` here?

**Comment by korywka** [comment]
I have profile, but it is my own gmail account:

<img width="312" alt="image" src="https://github.com/tomayac/opfs-explorer/assets/988471/e79657f8-eb60-49d0-a397-41bd8fd202d3">

```
Google Chrome | 117.0.5938.149 (Official Build) (arm64)
-- | --
Revision | e3344ddefa12e60436fa28c81cf207c1afb4d0a9-refs/branch-heads/5938@{#1539}
OS | macOS Version 14.0 (Build 23A344)
JavaScript | V8 11.7.439.21
User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Command Line | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --flag-switches-begin --flag-switches-end --origin-trial-disabled-features=WebGPU --disable-nacl
Executable Path | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Profile Path | /Users/korywka/Library/Application Support/Google/Chrome/Default
Linker | lld
Active variations | b6aa8178-ca7d8d806d1571c7-ca7d8d8078ce0fb-377be55a73440212-377be55a25a516b9-377be55a19306e3-377be55a3efb9579-377be55aa8066858-ca7d8d8060929057-377be55ab05e1e6c-ca7d8d80aa21b4f1-377be55a9dca89f8-377be55a5f8ff765-d6f282a8eddd0d82-7723ede9df41299a-ca7d8d80c23b87b6-b7a0c4b5aba1243e-ca7d8d80a84012f2-377be55ab6cffda3-ca7d8d803095aa95-3f4a17df89f2e43d-ca7d8d80d2e8e6e4-377be55a4555086c-ca7d8d807d41a07a-377be55ae4e743b0-ca7d8d80b4fb8450-ca7d8d80250dda8b-cd5781de28329b37-377be55ac3f415b4-377be55afba472a8-8d35b2061d0b1e05-744d50741e940a7c-ca7d8d8055380672-cdbea37c43bba9d8-7bcdc52d4749874c-28165b59da155734-ca7d8d80cd59be9a-ca7d8d8044666d99-ca7d8d80d555098c-dd8fab8ce5249c82-93c76e2df6f5c542-12ede6a21584cf60-ca7d8d8081b1a2c3-377be55a4aebab6e-377be55ab2cff759-12ede6a2a582a1b8-5ad3f43d5633b41a-ca7d8d80933702bb-10db844d92d97b4-ca7d8d80d97f772b-12ede6a287a22c16-2abeac9a1b8f1508-12ede6a21d865dc8-ca7d8d80a3ffdf1-ca7d8d803fd33f16-ca7d8d80c5055646-ca7d8d80194d8898-ca7d8d803a4ffe07-d0a24182c272f203-12ede6a26d27df64-9f7f68d9266af18d-ca7d8d80bbba1577-377be55a6fea66b3-ca7d8d80829fa6ed-377be55af782a8be-377be55a71c14987-ca7d8d80b27b7146-ca7d8d80bacf219a-ca7d8d80abaf0db8-ca7d8d8019705a3d-12ede6a28659ca17-377be55a910af27f-ca7d8d8093cefeeb-ca7d8d80178e8b37-a6d95901784a7e92-ca7d8d80bd60f05-377be55a2b4e7fda-e6036126ea90e0df-c416414c84f2bb65-ca7d8d80176b6657-28ad44af7b9a9e3-ca7d8d804b82c9ff-ca7d8d80c88fa1e2-ca7d8d8075ffb03a-377be55a9ccbeced-377be55acb87f652-c9fd69daca5a2953-12ede6a2da493d3c-ca7d8d803ed94085-4c2bb5d210ce7fc1-377be55aca12356a-377be55a5d1017fe-ca7d8d8014d411b8-a9197b0ed55357c-f8c48e3159a12fbe-67ede164bb73ab6c-ca7d8d805c4e748e-ca7d8d80ea23a088-f2eff9b5365085fd-f9a4370345a2f2f-388f734e28410024-377be55a137f6fe-ca7d8d809a382556-377be55a4ea303a6-ecbb250e4c3d08ef-ee63ae0278506c55-ca7d8d8094edc5b9-9e76aa6ea83da733-377be55a7c0d937f-ca7d8d805eb745a8-ca7d8d802468be5e-b258eb7130cf4980-ca7d8d8019e446cd-ca7d8d80d7d493f4-ca7d8d801edcddf4-2d58eb1b278baf51-4fe2a42f9a4b43c6-ca7d8d80116fcdbe-ca7d8d80a321e9ac-bbe4eb9cfd4b313c-873cd3a58a38784f-377be55a3f2823d1-299a91751918000d-efe652bbf82ee03-ca7d8d804a08d55f-ca7d8d807f19e54-ca7d8d80d0083347-ca7d8d80a36e888b-ca7d8d80788db06c-8035bf4cb46f46d-377be55af43e9210-ca7d8d80e5ade537-377be55a90860314-b13b69927ec047c2-ca7d8d80494d8760-52325d43eadcacdf-6bdfffe738fbb360-6bdfffe77b2873c2-1a864c863ac60855-486e2a9cf48c01d3-6451d70a63dcb6a3-2fa8505ee706e746-cafb6ecef296190c-96d262884442aae2-a90023b1f690cf64-6bdfffe7ed1d377-e1cc0f1475f0f0a0-e1cc0f14710c3f90-6bdfffe7e2b18481-bca011b3e7e71889-4ad6057548732c07-ca7d8d80858aa29b-f020e6fa857d3571-9f7f68d9c1e0d32e-6edc92c738639f6a-377be55a216c8a00-ca7d8d80dd08905f-4fbdb046450afa61-e780c97ae53e8ff0-b036fe15514700c0-b2cf01c6657f1834-17a8ee636dcf9601-ca7d8d80a38f69b3-ca7d8d803bd26dba-ca7d8d808d549a7a-5fe72c56


```

**Comment by tomayac** [comment]
Does it change if you update to `Version 118.0.5993.70 (Official Build) (arm64)`, the current stable version?

**Comment by korywka** [comment]
Nope :( just updated
<img width="703" alt="image" src="https://github.com/tomayac/opfs-explorer/assets/988471/f20fbf56-e490-402d-8ae5-3c2cc5870126">
<img width="1728" alt="image" src="https://github.com/tomayac/opfs-explorer/assets/988471/7fbec65d-d42b-486c-907f-d574774ec10c">
but it works in incognito:
<img width="1728" alt="image" src="https://github.com/tomayac/opfs-explorer/assets/988471/6c774b98-5824-496b-a811-21203286b8b6">
btw i just logged out from my account and it still doesnt work:
<img width="1728" alt="image" src="https://github.com/tomayac/opfs-explorer/assets/988471/0930332f-1f9d-479c-99c6-d5f2e2e0cec6">
only in incognito.

**Comment by tomayac** [comment]
I have asked our extensions team if they have a theory of what could be happening here… Thanks for your patience.

**Comment by oliverdunk** [comment]
Hey @korywka 👋  Could you go to chrome://flags and try setting `DevTools using Tab Target` to disabled? I wouldn't expect that to have an impact, but it's a large refactoring, so maybe it could help. If it doesn't, it would be great to know more generally if you have any specific flags turned on there :)

**Comment by korywka** [comment]
@oliverdunk Hi. Unfortunately it didn't help. I am ok with using incognito, but if you are interested in finding out the reason, we can continue :) it is surprising that it does not affect everyone. All my flags here are defaults:
<img width="747" alt="image" src="https://github.com/tomayac/opfs-explorer/assets/988471/caa6cd2c-6666-4956-adec-36a8c2951487">

**Comment by korywka** [comment]
Do not know if it helps. but at least tab is shown if I remove serviceworker script from manifest

https://github.com/tomayac/opfs-explorer/assets/988471/d45232b9-d89b-4a18-b3c6-679845ff5157

**Comment by tomayac** [comment]
Could it be a conflicting extension? I see an AdBlock tab in there… If you disable extensions 1:1, until (maybe) OPFS Explorer shows up, does that work?

**Comment by korywka** [comment]
Nope. But it works without incognito and without service worker:

https://github.com/tomayac/opfs-explorer/assets/988471/23cd773b-9cde-4a2c-9968-16f1422d2574

Do not know if SW is optionally here or some old is used after previous registration.
