### ISSUE TITLE
Saved files content preview

### ISSUE THREAD

**Issue by thanhnguyen2187** [tomayac/opfs-explorer#14]
Hi.

Many thanks for the awesome plugin!

However, for my use case, where I want to create an offline-first app and save my records to many different files, I found it quite inconvenient to download and view each of those files for debugging purpose. It would be really great if I can get a glimpse at those files in directly in the plugin tab.

![image](https://github.com/tomayac/opfs-explorer/assets/27758849/09f7ef46-1335-4108-96be-bbf61522e69b)

What do you think?

**Comment by tomayac** [comment]
Added direct previewing and editing of textual files:

![Screenshot 2023-10-18 at 13 48 14](https://github.com/tomayac/opfs-explorer/assets/145676/b9bb95ef-3045-4e16-9771-66e7ce80c6dd)
![Screenshot 2023-10-18 at 13 48 39](https://github.com/tomayac/opfs-explorer/assets/145676/12f2c956-5be2-4de3-b991-ed70e0a3785e)
