### ISSUE TITLE
Is this broken, or is it just me?

### ISSUE THREAD

**Issue by Matt-TOTW** [tomayac/opfs-explorer#15]
Hi there - is this extension broken or is it just me?
Chrome version = 120.0.6099.199 (latest as of this writing)
I am testing it on the test page: https://tomayac.github.io/opfs-explorer/
I do not see the tab in dev tools and the extension appears enabled but greyed out in my extensions menu
![image](https://github.com/tomayac/opfs-explorer/assets/36234834/39731e35-b151-4e89-8b5a-5a01733d378d)

Many thanks!

**Comment by tomayac** [comment]
Might be just you. I tested right now on `Version 120.0.6099.199 (Official Build) (arm64)` and it worked fine. Maybe some enterprise setting that disabled it?

**Comment by Matt-TOTW** [comment]
Damn - must be something like that I guess. Thanks for checking, I'll dig deeper.

**Comment by Matt-TOTW** [comment]
I'm not sure exactly what dev tools setting I had that broke it - but "Restore defaults and reload" under settings in dev tools did the trick. Sorry to waste your time, thanks for the quick reply.

**Comment by tomayac** [comment]
No worries at all. #TIL about this setting in DevTools, so thanks for sharing the solution `:-)`!

**Comment by steida** [comment]
@tomayac I think it should be added to the readme, "Restore defaults and reload", so other people will not have to read issues as I just did.

**Comment by tomayac** [comment]
Added in https://github.com/tomayac/opfs-explorer/commit/2d3e4164ef2f1a9f0a2b649bdca2eda9122149c7.
