### ISSUE TITLE
Extension somehow does not work on localhost

### ISSUE THREAD

**Issue by captainbrosset** [tomayac/opfs-explorer#2]
I'm not sure that this is related to using localhost, or something else. But here's what I did:

* Copied the source code from your demo page at https://tomayac.github.io/opfs-explorer/
* Created a local html file with the copied content.
* Started a local server to make the page available via http://localhost:8080/opfs.html
* Opened the page in Chrome Canary, with your extension installed

When I open DevTools and use the OPFS explorer extension panel, I only see a spinning loader, and the data never shows up.
If I open DevTools on DevTools, I can see the following error too:

```
Error handling response: TypeError: Cannot read properties of undefined (reading 'structure')
    at chrome-extension://acndjpgkpaclldomagafnognkcgjignd/devtools.js:111:21
```

A new error occurs every few seconds. I think the code is trying to refresh the panel on an interval or something.

**Comment by tomayac** [comment]
Thanks, fixed via https://github.com/tomayac/opfs-explorer/commit/22482ef1bc09a189aa585fcb2ee395c26411ec64. The version with the fix (`1.2.0`) is pending approval in the Chrome Web Store.
