### ISSUE TITLE
Unable to Download Root Directory in OPFS Explorer

### ISSUE THREAD

**Issue by shinshin86** [tomayac/opfs-explorer#20]
Hello,
Thank you for your work on OPFS Explorer!

I’m encountering an issue with the "Download All" feature. When I attempt to download the root directory, a message appears saying, "Can't open this folder because it contains system files," as shown in the attached screenshot.

![opfs-explorer_download-all](https://github.com/user-attachments/assets/cbe27762-d328-471d-a590-709c52ba637b)

I tested this behavior on the OPFS Explorer demo page, and it seems likely that the issue can be reproduced there as well.
Could you let me know if this is a limitation due to browser restrictions, or if it’s an issue within OPFS Explorer itself? Any guidance on how to proceed would be greatly appreciated.

Thank you very much for your assistance!
Best regards,

**Comment by tomayac** [comment]
You probably tried to download directly into your `Downloads` folder, which is [one of the blocked folders](https://wicg.github.io/file-system-access/#enumdef-wellknowndirectory) that you can't directly write to. The solution is to save to a subfolder, like `Downloads/foo`. On macOS, you can create a new folder directly in the **Save** dialog. Let me know if this doesn't work. I just went through the flow successfully myself:

![Screenshot 2024-10-29 at 11 06 06](https://github.com/user-attachments/assets/dce90524-3ad6-4349-837f-280dd1ae2ee7)

**Comment by shinshin86** [comment]
@tomayac Thank you for your response.
As you mentioned, I was indeed trying to download directly to the `Downloads` folder. By saving to `Downloads/foo` instead, I was able to complete the download without any issues.
I wasn’t aware of this restriction, so this was a valuable learning experience.
Thanks again!

**Comment by tomayac** [comment]
Happy to help, and glad it wasn't a bug `:-)`.
