### ISSUE TITLE
Retain folder toggle state when files change

### ISSUE THREAD

**Issue by schickling** [tomayac/opfs-explorer#9]
Currently whenever a file changes, the OPFS explorer resets the view state and collapses all folders - which can be very frustrating.

It would be great if the toggle UI state was retained when files change.

**Comment by tomayac** [comment]
There will be proper DevTools support soon where this feature will be added. The extension is an intermediate "good enough, not great" solution, so I will close this (very legitimate) feature request as "not planned".

**Comment by tomayac** [comment]
The Chromium bug to track for native OPFS support in DevTools is https://crbug.com/1284595.
